'use strict';
let uiLang='en';
// The tray menu already speaks four languages: i18n.rs resolves the user's locale to zh, ja, ko
// or ru, and main.cjs hands the result to this page as `lang_resolved`. The card understood only
// Russian, so a Chinese machine showed a translated menu above an English card. Everything a
// provider or this page can put on the card is keyed by that same language code below:
// TEXT for whole strings, PATTERNS for the ones carrying a number or a plan name, UI for the
// words the card writes itself. A language with no table falls back to English rather than
// showing half a translation, so adding one is only ever data.
const TEXT={
  ko:{
    'Included usage':'포함 사용량',
    'API usage':'API 사용량',
    'On demand':'온디맨드',
    'Usage':'사용량',
    'Current session':'현재 세션',
    'Weekly (all models)':'주간 (모든 모델)',
    'Weekly (Opus)':'주간 (Opus)',
    'Weekly (model-scoped)':'주간 (모델별)',
    'Weekly limit':'주간 제한',
    'Weekly Limit':'주간 제한',
    '5-Hour Limit':'5시간 제한',
    '5-hour Limit':'5시간 제한',
    'Gemini Models':'Gemini 모델',
    'Claude and GPT models':'Claude 및 GPT 모델',
    'Monthly limit':'월간 제한',
    'Monthly Limit':'월간 제한',
    'Longer window':'장기 사용 기간',
    'Requests today · no limit published':'오늘 요청 수 · 한도 미공개',
    'Resetting…':'재설정 중…',
    'Resets at':'재설정 시각',
    'Resets':'재설정',
    'Working':'작업 중',
    'Waiting':'대기 중',
    'Streaming (network)':'스트리밍 중 (네트워크)',
    'Rate limited, retrying in':'요청 제한, 재시도까지',
    'Rate limited. retrying in':'요청 제한. 재시도까지',
    'request today':'오늘 요청',
    'requests today':'오늘 요청',
    'no requests today':'오늘 요청 없음',
    'Waiting for first reading…':'첫 측정값을 기다리는 중…',
    'Sign in to Claude Code to see usage.':'사용량을 확인하려면 Claude Code에 로그인하십시오.',
    'Sign in to Cursor to see usage.':'사용량을 확인하려면 Cursor에 로그인하십시오.',
    'Sign in to Codex to see usage.':'사용량을 확인하려면 Codex에 로그인하십시오.',
    'Sign in to Antigravity to see usage.':'사용량을 확인하려면 Antigravity에 로그인하십시오.',
    'needs your input':'응답을 기다리는 중',
    'Working in':'작업 위치:',
    'Sign in':'로그인',
    'Signing in...':'로그인 중…',
    'Refresh':'새로 고침',
    'Browser sign-in through Claude Code':'Claude Code를 통한 브라우저 로그인',
    'Complete sign-in in the browser or terminal window.':'브라우저나 터미널 창에서 로그인을 완료하십시오.',
    'Sign-in complete. Refreshing usage...':'로그인되었습니다. 사용량을 새로 고치는 중…',
    'Sign-in cancelled, failed or timed out. Try again.':'로그인이 취소되거나 실패했거나 시간이 초과되었습니다. 다시 시도하십시오.',
    'Checking usage...':'사용량 확인 중…',
    'Rate limited. Wait for the retry deadline.':'요청이 제한되었습니다. 재시도 시점까지 기다리십시오.',
    'Claude Code CLI not found. Install the standalone CLI first.':'Claude Code CLI를 찾을 수 없습니다. 먼저 독립 실행형 CLI를 설치하십시오.',
    'Claude sign-in or renewal is already running.':'Claude 로그인 또는 갱신이 이미 진행 중입니다.',
    'Unable to open Claude sign-in window.':'Claude 로그인 창을 열 수 없습니다.',
    'Claude HTTP 403: access denied. Check network or account access; sign-in may still be valid.':'Claude HTTP 403: 접근이 거부되었습니다. 네트워크나 계정의 접근 권한을 확인하십시오. 로그인은 여전히 유효할 수 있습니다.',
    'Run grok login to see usage.':'사용량을 확인하려면 grok login을 실행하십시오.',
  },
  'pt-BR':{
    'Included usage':'Uso incluído',
    'Sign in':'Entrar',
    'Signing in...':'Entrando...',
    'Refresh':'Atualizar',
    'Browser sign-in through Claude Code':'Login pelo navegador via Claude Code',
    'Complete sign-in in the browser or terminal window.':'Conclua o login no navegador ou na janela do terminal.',
    'Sign-in complete. Refreshing usage...':'Login concluído. Atualizando uso...',
    'Sign-in cancelled, failed or timed out. Try again.':'O login foi cancelado, falhou ou expirou. Tente novamente.',
    'Checking usage...':'Verificando uso...',
    'Rate limited. Wait for the retry deadline.':'Limite de requisições atingido. Aguarde o prazo para nova tentativa.',
    'Claude Code CLI not found. Install the standalone CLI first.':'CLI do Claude Code não encontrada. Instale primeiro a CLI independente.',
    'Claude sign-in or renewal is already running.':'O login ou a renovação do Claude já está em andamento.',
    'Unable to open Claude sign-in window.':'Não foi possível abrir a janela de login do Claude.',
    'Claude HTTP 403: access denied. Check network or account access; sign-in may still be valid.':'Claude HTTP 403: acesso negado. Verifique a rede ou o acesso da conta; o login ainda pode ser válido.',
    'API usage':'Uso da API',
    'On demand':'Sob demanda',
    'Usage':'Uso',
    'Current session':'Sessão atual',
    'Weekly (all models)':'Semanal (todos os modelos)',
    'Weekly (Opus)':'Semanal (Opus)',
    'Weekly (model-scoped)':'Semanal (por modelo)',
    'Weekly limit':'Limite semanal',
    'Weekly Limit':'Limite semanal',
    '5-Hour Limit':'Limite de 5 horas',
    '5-hour Limit':'Limite de 5 horas',
    'Gemini Models':'Modelos Gemini',
    'Claude and GPT models':'Modelos Claude e GPT',
    'Monthly limit':'Limite mensal',
    'Monthly Limit':'Limite mensal',
    'Longer window':'Janela mais longa',
    'Requests today · no limit published':'Solicitações hoje · nenhum limite publicado',
    'Updated':'Atualizado',
    'Resetting…':'Renovando…',
    'Resets at':'Redefine às',
    'Resets':'Redefine',
    'Working':'Trabalhando',
    'Waiting':'Aguardando',
    'Streaming (network)':'Transmitindo (rede)',
    'Rate limited, retrying in':'Limite de requisições, nova tentativa em',
    'Rate limited. retrying in':'Limite de requisições. nova tentativa em',
    'request today':'requisição hoje',
    'requests today':'requisições hoje',
    'no requests today':'nenhuma solicitação hoje',
    'Waiting for first reading…':'Aguardando a primeira leitura…',
    'Sign in to Claude Code to see usage.':'Entre no Claude Code para ver o uso.',
    'Sign in to Cursor to see usage.':'Entre no Cursor para ver o uso.',
    'Sign in to Codex to see usage.':'Entre no Codex para ver o uso.',
    'Sign in to Antigravity to see usage.':'Entre no Antigravity para ver o uso.',
    'Run grok login to see usage.':'Execute grok login para ver o uso.',
    'Run opencode auth login to see usage.':'Execute opencode auth login para ver o uso.',
    'No OpenCode Go subscription on this account':'Nenhuma assinatura do OpenCode Go nesta conta',
    'needs your input':'precisa da sua resposta',
    'Working in':'Em execução em'
  },
  uk:{
    'Included usage':'Використання в тарифі',
    'API usage':'Використання API',
    'On demand':'За потребою',
    'Usage':'Використання',
    'Current session':'Поточна сесія',
    'Weekly (all models)':'Тижневий (усі моделі)',
    'Weekly (Opus)':'Тижневий (Opus)',
    'Weekly (model-scoped)':'Тижневий (для вибраної моделі)',
    'Weekly limit':'Тижневий ліміт',
    'Weekly Limit':'Тижневий ліміт',
    '5-Hour Limit':'Ліміт 5 годин',
    '5-hour Limit':'Ліміт 5 годин',
    'Gemini Models':'Моделі Gemini',
    'Claude and GPT models':'Моделі Claude і GPT',
    'Monthly limit':'Місячний ліміт',
    'Monthly Limit':'Місячний ліміт',
    'Longer window':'Довше вікно',
    'Requests today · no limit published':'Запитів сьогодні · ліміт не опубліковано',
    'Resetting…':'Скидання…',
    'Resets at':'Скидання о',
    'Resets':'Скидання',
    'Working':'Працює',
    'Waiting':'Очікує',
    'Streaming (network)':'Потокова передача (мережа)',
    'Rate limited, retrying in':'Ліміт запитів, повтор через',
    'Rate limited. retrying in':'Ліміт запитів. повтор через',
    'request today':'запит сьогодні',
    'requests today':'запитів сьогодні',
    'no requests today':'сьогодні запитів немає',
    'Waiting for first reading…':'Очікування першого показника…',
    'Sign in to Claude Code to see usage.':'Увійдіть у Claude Code, щоб бачити використання.',
    'Sign in to Cursor to see usage.':'Увійдіть у Cursor, щоб бачити використання.',
    'Sign in to Codex to see usage.':'Увійдіть у Codex, щоб бачити використання.',
    'Sign in to Antigravity to see usage.':'Увійдіть в Antigravity, щоб бачити використання.',
    'needs your input':'потрібна ваша відповідь',
    'Working in':'Працює в'
  },
  ru:{
    'Included usage':'Включённое использование',
    'Sign in':'Авторизоваться',
    'Signing in...':'Вход…',
    'Browser sign-in through Claude Code':'Вход через браузер с помощью Claude Code',
    'Complete sign-in in the browser or terminal window.':'Подтвердите вход в браузере или окне терминала.',
    'Sign-in complete. Refreshing usage...':'Вход выполнен. Обновляю лимиты…',
    'Sign-in cancelled, failed or timed out. Try again.':'Вход отменён, завершился ошибкой или истекло время ожидания. Попробуйте ещё раз.',
    'Claude Code CLI not found. Install the standalone CLI first.':'Claude Code CLI не найден. Установите отдельный CLI.',
    'Claude sign-in or renewal is already running.':'Вход или обновление авторизации Claude уже выполняется.',
    'Unable to open Claude sign-in window.':'Не удалось открыть окно входа Claude.',
    'Claude HTTP 403: access denied. Check network or account access; sign-in may still be valid.':'Claude HTTP 403: доступ запрещён. Проверьте сеть и доступ к аккаунту; авторизация может быть действующей.',
    'API usage':'Использование API',
    'On demand':'По запросу',
    'Usage':'Использование',
    'Current session':'Текущий сеанс',
    'Weekly (all models)':'Недельный (все модели)',
    'Weekly (Opus)':'Недельный (Opus)',
    'Weekly (model-scoped)':'Недельный (для выбранной модели)',
    'Weekly limit':'Недельный лимит',
    'Weekly Limit':'Недельный лимит',
    '5-Hour Limit':'Лимит на 5 часов',
    '5-hour Limit':'Лимит на 5 часов',
    'Gemini Models':'Модели Gemini',
    'Claude and GPT models':'Модели Claude и GPT',
    'Monthly limit':'Месячный лимит',
    'Monthly Limit':'Месячный лимит',
    'Longer window':'Более длительный период',
    'Requests today · no limit published':'Запросы сегодня · лимит не опубликован',
    'Resetting…':'Сброс…',
    'Resets at':'Сброс в',
    'Resets':'Сброс',
    'Working':'Работа',
    'Waiting':'Ожидание',
    'Streaming (network)':'Потоковая передача (сеть)',
    'Rate limited, retrying in':'Превышен лимит, повтор через',
    'Rate limited. retrying in':'Превышен лимит. повтор через',
    'request today':'запрос сегодня',
    'requests today':'запросов сегодня',
    'no requests today':'сегодня запросов нет',
    'Waiting for first reading…':'Ожидание первого показания…',
    'Sign in to Claude Code to see usage.':'Войдите в Claude Code, чтобы увидеть использование.',
    'Sign in to Cursor to see usage.':'Войдите в Cursor, чтобы увидеть использование.',
    'Sign in to Codex to see usage.':'Войдите в Codex, чтобы увидеть использование.',
    'Sign in to Antigravity to see usage.':'Войдите в Antigravity, чтобы увидеть использование.',
    'Run grok login to see usage.':'Выполните grok login, чтобы увидеть использование.',
    'needs your input':'требуется ваш ответ',
    'Working in':'Работает в'
  },
  zh:{
    'Included usage':'包含用量',
    'API usage':'API 用量',
    'On demand':'按需用量',
    'Usage':'用量',
    'Current session':'当前会话',
    'Weekly (all models)':'每周（全部模型）',
    'Weekly (Opus)':'每周（Opus）',
    'Weekly (model-scoped)':'每周（指定模型）',
    'Weekly limit':'每周限额',
    'Weekly Limit':'每周限额',
    '5-Hour Limit':'5 小时限额',
    '5-hour Limit':'5 小时限额',
    'Gemini Models':'Gemini 模型',
    'Claude and GPT models':'Claude 与 GPT 模型',
    'Monthly limit':'每月限额',
    'Monthly Limit':'每月限额',
    'Longer window':'更长的周期',
    'Requests today · no limit published':'今日请求数 · 未公布限额',
    'Resetting…':'正在重置…',
    'Resets at':'重置于',
    'Resets':'重置',
    'Working':'工作中',
    'Waiting':'等待中',
    'Streaming (network)':'正在传输（网络）',
    'Rate limited, retrying in':'已限流，稍后重试',
    'Rate limited. retrying in':'已限流. 稍后重试',
    'request today':'次请求（今日）',
    'requests today':'次请求（今日）',
    'no requests today':'今日没有请求',
    'Waiting for first reading…':'正在等待第一次读数…',
    'Sign in to Claude Code to see usage.':'请登录 Claude Code 以查看用量。',
    'Sign in to Cursor to see usage.':'请登录 Cursor 以查看用量。',
    'Sign in to Codex to see usage.':'请登录 Codex 以查看用量。',
    'Sign in to Antigravity to see usage.':'请登录 Antigravity 以查看用量。',
    'Run grok login to see usage.':'请运行 grok login 以查看用量。',
    'needs your input':'等待你的输入',
    'Working in':'工作于',
  },
  'zh-Hant':{
    'Included usage':'包含用量',
    'API usage':'API 用量',
    'On demand':'按需用量',
    'Usage':'用量',
    'Current session':'目前工作階段',
    'Weekly (all models)':'每週（全部模型）',
    'Weekly (Opus)':'每週（Opus）',
    'Weekly (model-scoped)':'每週（指定模型）',
    'Weekly limit':'每週限額',
    'Weekly Limit':'每週限額',
    '5-Hour Limit':'5 小時限額',
    '5-hour Limit':'5 小時限額',
    'Gemini Models':'Gemini 模型',
    'Claude and GPT models':'Claude 與 GPT 模型',
    'Monthly limit':'每月限額',
    'Monthly Limit':'每月限額',
    'Longer window':'更長的週期',
    'Requests today · no limit published':'今日要求數 · 未公布限額',
    'Resetting…':'正在重置…',
    'Resets at':'重置於',
    'Resets':'重置',
    'Working':'工作中',
    'Waiting':'等待中',
    'Streaming (network)':'正在傳輸（網路）',
    'Rate limited, retrying in':'已限流，稍後重試',
    'Rate limited. retrying in':'已限流. 稍後重試',
    'request today':'次要求（今日）',
    'requests today':'次要求（今日）',
    'no requests today':'今日沒有要求',
    'Waiting for first reading…':'正在等待第一次讀數…',
    'Sign in to Claude Code to see usage.':'請登入 Claude Code 以查看用量。',
    'Sign in to Cursor to see usage.':'請登入 Cursor 以查看用量。',
    'Sign in to Codex to see usage.':'請登入 Codex 以查看用量。',
    'Sign in to Antigravity to see usage.':'請登入 Antigravity 以查看用量。',
    'Run grok login to see usage.':'請執行 grok login 以查看用量。',
    'needs your input':'等待你的輸入',
    'Working in':'工作於',
  },
};
// Kept as patterns rather than exact keys: each one carries a number, a plan name or an error
// the provider wrote, so the whole string can never be a dictionary key.
const PATTERNS={
  ko:[
    [/^(\d+)m limit$/,'$1분 제한'],
    [/^(\d+)h limit$/,'$1시간 제한'],
    [/^(\d+)d limit$/,'$1일 제한'],
    [/^Rate limited, retrying in (\d+)s$/,'요청 제한, $1초 후 재시도'],
    [/^Rate limited. retrying in (\d+)s$/,'요청 제한. $1초 후 재시도'],
    [/^Unlimited on the (.+) plan. nothing to meter$/,'$1 요금제는 무제한입니다. 측정할 사용량이 없습니다'],
    [/^The (.+) plan has nothing for Cursor to meter yet$/,'$1 요금제에는 아직 Cursor가 측정할 사용량이 없습니다'],
    [/^(.+) · Google publishes no quota for this account$/,'$1 · Google이 이 계정의 할당량을 공개하지 않습니다'],
    [/^Live read failed \((.+)\)$/,'실시간 조회 실패 ($1)'],
    [/Weekly \(all models\)/g,'주간 (모든 모델)'],
    [/Weekly \(Opus\)/g,'주간 (Opus)'],
    [/Weekly \(model-scoped\)/g,'주간 (모델별)'],
    [/Weekly limit/g,'주간 제한'],
    [/Monthly limit/g,'월간 제한'],
    [/\bWeekly\b/g,'주간'],
    [/\bMonthly\b/g,'월간'],
    [/ · via /g,' · 경유: '],
    [/needs your input/g,'응답을 기다리는 중'],
    [/^Working in /,'작업 위치: '],
    [/via Antigravity CLI/g,'Antigravity CLI 경유'],
    [/via Antigravity/g,'Antigravity 경유'],
    [/via Google/g,'Google 경유'],
    [/No Claude Code credential found/g,'Claude Code 자격 증명을 찾을 수 없습니다'],
    [/Credential expired. run claude once in a terminal to renew it/g,'자격 증명이 만료되었습니다. 터미널에서 claude를 한 번 실행해 갱신하십시오'],
    [/Credential rejected \(switched accounts\?\)/g,'자격 증명이 거부되었습니다 (계정을 전환하셨습니까?)'],
    [/Codex sign-in expired. open Codex once to refresh it/g,'Codex 로그인이 만료되었습니다. Codex를 한 번 열어 갱신하십시오'],
    [/Codex rejected its sign-in. sign in to Codex again/g,'Codex 로그인이 거부되었습니다. Codex에 다시 로그인하십시오'],
    [/Codex reported no usage windows/g,'Codex가 사용량 집계 기간을 보고하지 않았습니다'],
    [/Codex has not recorded a usage snapshot yet/g,'Codex가 아직 사용량 스냅샷을 기록하지 않았습니다'],
    [/from last Codex run/g,'마지막 Codex 실행 기준'],
    [/Waiting for Antigravity CLI quota/g,'Antigravity CLI 할당량을 기다리는 중'],
    [/Open Antigravity to read its quota/g,'할당량을 확인하려면 Antigravity를 여십시오'],
    [/Antigravity's Google session was rejected. sign in again in Antigravity/g,'Antigravity의 Google 세션이 거부되었습니다. Antigravity에서 다시 로그인하십시오'],
    [/Antigravity is closed. last reading kept/g,'Antigravity가 닫혀 있습니다. 마지막 측정값 유지'],
    [/Sign in to Cursor \(the editor\) to see usage\./g,'사용량을 확인하려면 Cursor 편집기에 로그인하십시오.'],
    [/Cursor session was rejected. sign in again in the editor/g,'Cursor 세션이 거부되었습니다. 편집기에서 다시 로그인하십시오'],
  ],
  'pt-BR':[
    [/^(\d+)m limit$/,'Limite de $1 min'],
    [/^(\d+)h limit$/,'Limite de $1 h'],
    [/^(\d+)d limit$/,'Limite de $1 d'],
    [/^Rate limited, retrying in (\d+)s$/,'Limite de requisições, nova tentativa em $1 s'],
    [/^Rate limited. retrying in (\d+)s$/,'Limite de requisições. nova tentativa em $1 s'],
    [/^Unlimited on the (.+) plan. nothing to meter$/,'Ilimitado no plano $1. nada para medir'],
    [/^The (.+) plan has nothing for Cursor to meter yet$/,'O plano $1 ainda não tem uso para o Cursor medir'],
    [/^(.+) · Google publishes no quota for this account$/,'$1 · Google não publica cota para esta conta'],
    [/^Live read failed \((.+)\)$/,'Falha na leitura em tempo real ($1)'],
    [/Weekly \(all models\)/g,'Semanal (todos os modelos)'],
    [/Weekly \(Opus\)/g,'Semanal (Opus)'],
    [/Weekly \(model-scoped\)/g,'Semanal (por modelo)'],
    [/Weekly limit/g,'Limite semanal'],
    [/Monthly limit/g,'Limite mensal'],
    [/\bWeekly\b/g,'Semanal'],
    [/\bMonthly\b/g,'Mensal'],
    [/ · via /g,' · via '],
    [/needs your input/g,'precisa da sua resposta'],
    [/^Working in /,'Em execução em '],
    [/via Antigravity CLI/g,'via Antigravity CLI'],
    [/via Antigravity/g,'via Antigravity'],
    [/via Google/g,'via Google'],
    [/No Claude Code credential found/g,'Credencial do Claude Code não encontrada'],
    [/Credential expired. run claude once in a terminal to renew it/g,'A credencial expirou. execute claude uma vez no terminal para renová-la'],
    [/Credential rejected \(switched accounts\?\)/g,'Credencial rejeitada (você trocou de conta?)'],
    [/Codex sign-in expired. open Codex once to refresh it/g,'O login do Codex expirou. abra o Codex uma vez para atualizá-lo'],
    [/Codex rejected its sign-in. sign in to Codex again/g,'O Codex rejeitou o login. entre novamente no Codex'],
    [/Codex reported no usage windows/g,'O Codex não informou nenhuma janela de uso'],
    [/Codex has not recorded a usage snapshot yet/g,'O Codex ainda não registrou um retrato de uso'],
    [/from last Codex run/g,'da última execução do Codex'],
    [/Waiting for Antigravity CLI quota/g,'Aguardando a cota da CLI do Antigravity'],
    [/Open Antigravity to read its quota/g,'Abra o Antigravity para ler a cota'],
    [/Antigravity's Google session was rejected. sign in again in Antigravity/g,'A sessão Google do Antigravity foi rejeitada. entre novamente no Antigravity'],
    [/Antigravity is closed. last reading kept/g,'O Antigravity está fechado. última leitura mantida'],
    [/Sign in to Cursor \(the editor\) to see usage\./g,'Entre no Cursor (o editor) para ver o uso.'],
    [/Cursor session was rejected. sign in again in the editor/g,'A sessão do Cursor foi rejeitada. entre novamente no editor'],
  ],
  uk:[
    [/^(\d+)m limit$/,'Ліміт $1 хв'],
    [/^(\d+)h limit$/,'Ліміт $1 год'],
    [/^(\d+)d limit$/,'Ліміт $1 дн'],
    [/^Rate limited, retrying in (\d+)s$/,'Ліміт запитів, повтор через $1 с'],
    [/^Rate limited. retrying in (\d+)s$/,'Ліміт запитів. повтор через $1 с'],
    [/^Unlimited on the (.+) plan. nothing to meter$/,'Безліміт на тарифі $1. нічого вимірювати'],
    [/^The (.+) plan has nothing for Cursor to meter yet$/,'У тарифі $1 Cursor поки нічого вимірювати'],
    [/^(.+) · Google publishes no quota for this account$/,'$1 · Google не публікує ліміт для цього акаунта'],
    [/^Live read failed \((.+)\)$/,'Не вдалося прочитати наживо ($1)'],
    [/Weekly \(all models\)/g,'Тижневий (усі моделі)'],
    [/Weekly \(Opus\)/g,'Тижневий (Opus)'],
    [/Weekly \(model-scoped\)/g,'Тижневий (для вибраної моделі)'],
    [/Weekly limit/g,'Тижневий ліміт'],
    [/Monthly limit/g,'Місячний ліміт'],
    [/\bWeekly\b/g,'Тижневий'],
    [/\bMonthly\b/g,'Місячний'],
    [/ · via /g,' · через '],
    [/needs your input/g,'потрібна ваша відповідь'],
    [/^Working in /,'Працює в '],
    [/via Antigravity CLI/g,'через Antigravity CLI'],
    [/via Antigravity/g,'через Antigravity'],
    [/via Google/g,'через Google'],
    [/No Claude Code credential found/g,'Не знайдено облікових даних Claude Code'],
    [/Credential expired. run claude once in a terminal to renew it/g,'Термін дії облікових даних минув. запустіть claude один раз у терміналі, щоб поновити їх'],
    [/Credential rejected \(switched accounts\?\)/g,'Облікові дані відхилено (змінили акаунт?)'],
    [/Codex sign-in expired. open Codex once to refresh it/g,'Термін входу в Codex минув. відкрийте Codex один раз, щоб поновити'],
    [/Codex rejected its sign-in. sign in to Codex again/g,'Codex відхилив вхід. увійдіть у Codex ще раз'],
    [/Codex reported no usage windows/g,'Codex не повернув жодного вікна використання'],
    [/Codex has not recorded a usage snapshot yet/g,'Codex ще не записав знімок використання'],
    [/from last Codex run/g,'з останнього запуску Codex'],
    [/Waiting for Antigravity CLI quota/g,'Очікування ліміту Antigravity CLI'],
    [/Open Antigravity to read its quota/g,'Відкрийте Antigravity, щоб прочитати його ліміт'],
    [/Antigravity's Google session was rejected. sign in again in Antigravity/g,'Сеанс Google в Antigravity відхилено. увійдіть в Antigravity ще раз'],
    [/Antigravity is closed. last reading kept/g,'Antigravity закрито. збережено останній показник'],
    [/Sign in to Cursor \(the editor\) to see usage\./g,'Увійдіть у Cursor (редактор), щоб бачити використання.'],
    [/Cursor session was rejected. sign in again in the editor/g,'Сеанс Cursor відхилено. увійдіть у редакторі ще раз'],
  ],
  ru:[
    [/^(\d+)m limit$/,'Лимит на $1 мин'],
    [/^(\d+)h limit$/,'Лимит на $1 ч'],
    [/^(\d+)d limit$/,'Лимит на $1 дн.'],
    [/^Rate limited, retrying in (\d+)s$/,'Превышен лимит, повтор через $1 с'],
    [/^Rate limited. retrying in (\d+)s$/,'Превышен лимит. повтор через $1 с'],
    [/^Unlimited on the (.+) plan. nothing to meter$/,'Безлимитный тариф $1. нечего измерять'],
    [/^The (.+) plan has nothing for Cursor to meter yet$/,'В тарифе $1 пока нечего измерять Cursor'],
    [/^(.+) · Google publishes no quota for this account$/,'$1 · Google не публикует лимит для этого аккаунта'],
    [/^Live read failed \((.+)\)$/,'Ошибка чтения онлайн-данных ($1)'],
    [/Weekly \(all models\)/g,'Недельный (все модели)'],
    [/Weekly \(Opus\)/g,'Недельный (Opus)'],
    [/Weekly \(model-scoped\)/g,'Недельный (для выбранной модели)'],
    [/Weekly limit/g,'Недельный лимит'],
    [/Monthly limit/g,'Месячный лимит'],
    [/\bWeekly\b/g,'Недельный'],
    [/\bMonthly\b/g,'Месячный'],
    [/ · via /g,' · через '],
    [/needs your input/g,'требуется ваш ответ'],
    [/^Working in /,'Работает в '],
    [/via Antigravity CLI/g,'через CLI Antigravity'],
    [/via Antigravity/g,'через Antigravity'],
    [/via Google/g,'через Google'],
    [/No Claude Code credential found/g,'Учётные данные Claude Code не найдены'],
    [/Credential expired. run claude once in a terminal to renew it/g,'Учётные данные истекли. запустите claude в терминале один раз, чтобы обновить их'],
    [/Credential rejected \(switched accounts\?\)/g,'Учётные данные отклонены (вы сменили аккаунт?)'],
    [/Codex sign-in expired. open Codex once to refresh it/g,'Срок входа в Codex истёк. откройте Codex для обновления'],
    [/Codex rejected its sign-in. sign in to Codex again/g,'Codex отклонил вход. войдите в Codex снова'],
    [/Codex reported no usage windows/g,'Codex не сообщил окна использования'],
    [/Codex has not recorded a usage snapshot yet/g,'Codex ещё не записал снимок использования'],
    [/from last Codex run/g,'из последнего запуска Codex'],
    [/Waiting for Antigravity CLI quota/g,'Ожидание квоты Antigravity CLI'],
    [/Open Antigravity to read its quota/g,'Откройте Antigravity, чтобы получить квоту'],
    [/Antigravity's Google session was rejected. sign in again in Antigravity/g,'Сеанс Google в Antigravity отклонён. войдите в Antigravity снова'],
    [/Antigravity is closed. last reading kept/g,'Antigravity закрыт. сохранено последнее показание'],
    [/Sign in to Cursor \(the editor\) to see usage\./g,'Войдите в Cursor (редактор), чтобы увидеть использование.'],
    [/Cursor session was rejected. sign in again in the editor/g,'Сеанс Cursor отклонён. снова войдите в редакторе'],
  ],
  zh:[
    [/^(\d+)m limit$/,'$1 分钟限额'],
    [/^(\d+)h limit$/,'$1 小时限额'],
    [/^(\d+)d limit$/,'$1 天限额'],
    [/^Rate limited, retrying in (\d+)s$/,'已限流，$1 秒后重试'],
    [/^Rate limited. retrying in (\d+)s$/,'已限流. $1 秒后重试'],
    [/^Unlimited on the (.+) plan. nothing to meter$/,'$1 套餐不限量. 没有可计量的项目'],
    [/^The (.+) plan has nothing for Cursor to meter yet$/,'$1 套餐暂时没有可供 Cursor 计量的用量'],
    [/^(.+) · Google publishes no quota for this account$/,'$1 · Google 未公布该账号的配额'],
    [/^Live read failed \((.+)\)$/,'实时读取失败（$1）'],
    [/Weekly \(all models\)/g,'每周（全部模型）'],
    [/Weekly \(Opus\)/g,'每周（Opus）'],
    [/Weekly \(model-scoped\)/g,'每周（指定模型）'],
    [/Weekly limit/g,'每周限额'],
    [/Monthly limit/g,'每月限额'],
    [/\bWeekly\b/g,'每周'],
    [/\bMonthly\b/g,'每月'],
    [/ · via /g,' · 来自 '],
    [/needs your input/g,'等待你的输入'],
    [/^Working in /,'工作于 '],
    [/via Antigravity CLI/g,'来自 Antigravity CLI'],
    [/via Antigravity/g,'来自 Antigravity'],
    [/via Google/g,'来自 Google'],
    [/No Claude Code credential found/g,'未找到 Claude Code 凭证'],
    [/Credential expired. run claude once in a terminal to renew it/g,'凭证已过期. 在终端里运行一次 claude 即可续期'],
    [/Credential rejected \(switched accounts\?\)/g,'凭证被拒绝（换过账号？）'],
    [/Codex sign-in expired. open Codex once to refresh it/g,'Codex 登录已过期. 打开一次 Codex 即可刷新'],
    [/Codex rejected its sign-in. sign in to Codex again/g,'Codex 拒绝了它的登录. 请重新登录 Codex'],
    [/Codex reported no usage windows/g,'Codex 没有报告任何用量周期'],
    [/Codex has not recorded a usage snapshot yet/g,'Codex 还没有记录过用量快照'],
    [/from last Codex run/g,'来自上次 Codex 运行'],
    [/Waiting for Antigravity CLI quota/g,'正在等待 Antigravity CLI 的配额'],
    [/Open Antigravity to read its quota/g,'打开 Antigravity 以读取配额'],
    [/Antigravity's Google session was rejected. sign in again in Antigravity/g,'Antigravity 的 Google 会话被拒绝. 请在 Antigravity 中重新登录'],
    [/Antigravity is closed. last reading kept/g,'Antigravity 已关闭. 保留上一次读数'],
    [/Sign in to Cursor \(the editor\) to see usage\./g,'请登录 Cursor（编辑器）以查看用量。'],
    [/Cursor session was rejected. sign in again in the editor/g,'Cursor 会话被拒绝. 请在编辑器中重新登录'],
  ],
  'zh-Hant':[
    [/^(\d+)m limit$/,'$1 分鐘限額'],
    [/^(\d+)h limit$/,'$1 小時限額'],
    [/^(\d+)d limit$/,'$1 天限額'],
    [/^Rate limited, retrying in (\d+)s$/,'已限流，$1 秒後重試'],
    [/^Rate limited. retrying in (\d+)s$/,'已限流. $1 秒後重試'],
    [/^Unlimited on the (.+) plan. nothing to meter$/,'$1 方案不限量. 沒有可計量的項目'],
    [/^The (.+) plan has nothing for Cursor to meter yet$/,'$1 方案暫時沒有可供 Cursor 計量的用量'],
    [/^(.+) · Google publishes no quota for this account$/,'$1 · Google 未公布該帳號的配額'],
    [/^Live read failed \((.+)\)$/,'即時讀取失敗（$1）'],
    [/Weekly \(all models\)/g,'每週（全部模型）'],
    [/Weekly \(Opus\)/g,'每週（Opus）'],
    [/Weekly \(model-scoped\)/g,'每週（指定模型）'],
    [/Weekly limit/g,'每週限額'],
    [/Monthly limit/g,'每月限額'],
    [/\bWeekly\b/g,'每週'],
    [/\bMonthly\b/g,'每月'],
    [/ · via /g,' · 來自 '],
    [/needs your input/g,'等待你的輸入'],
    [/^Working in /,'工作於 '],
    [/via Antigravity CLI/g,'來自 Antigravity CLI'],
    [/via Antigravity/g,'來自 Antigravity'],
    [/via Google/g,'來自 Google'],
    [/No Claude Code credential found/g,'未找到 Claude Code 憑證'],
    [/Credential expired. run claude once in a terminal to renew it/g,'憑證已過期. 在終端機裡執行一次 claude 即可續期'],
    [/Credential rejected \(switched accounts\?\)/g,'憑證被拒絕（換過帳號？）'],
    [/Codex sign-in expired. open Codex once to refresh it/g,'Codex 登入已過期. 開啟一次 Codex 即可重新整理'],
    [/Codex rejected its sign-in. sign in to Codex again/g,'Codex 拒絕了它的登入. 請重新登入 Codex'],
    [/Codex reported no usage windows/g,'Codex 沒有報告任何用量週期'],
    [/Codex has not recorded a usage snapshot yet/g,'Codex 還沒有記錄過用量快照'],
    [/from last Codex run/g,'來自上次 Codex 執行'],
    [/Waiting for Antigravity CLI quota/g,'正在等待 Antigravity CLI 的配額'],
    [/Open Antigravity to read its quota/g,'開啟 Antigravity 以讀取配額'],
    [/Antigravity's Google session was rejected. sign in again in Antigravity/g,'Antigravity 的 Google 工作階段被拒絕. 請在 Antigravity 中重新登入'],
    [/Antigravity is closed. last reading kept/g,'Antigravity 已關閉. 保留上一次讀數'],
    [/Sign in to Cursor \(the editor\) to see usage\./g,'請登入 Cursor（編輯器）以查看用量。'],
    [/Cursor session was rejected. sign in again in the editor/g,'Cursor 工作階段被拒絕. 請在編輯器中重新登入'],
  ],
};
// Grammar differs enough that a format string would not carry it. Russian puts the verb last,
// Chinese puts it after the time. so each language writes its own short functions.
const UI={
  ko:{locale:'ko-KR',title:n=>n,resetting:'재설정 중…',resetsIn:m=>`${m}분 후 재설정`,
      resetsAt:t=>`${t}에 재설정`,resetsOn:(d,t)=>`${d} ${t}에 재설정`,resetsDate:d=>`${d}에 재설정`,
      ago:m=>m<60?`${m}분 전`:`${Math.round(m/60)}시간 전`,
      usedLeft:(used,left)=>`${used}% 사용 · ${left}% 남음`,
      left:v=>`${v}% 남음`,resets:n=>`재설정 ${n}회 사용 가능`,until:d=>`${d}까지`,never:'만료 없음',unknown:'만료일 알 수 없음',
      kick:{warning:'사용량 경고',limit:'한도 도달',waiting:'확인 필요',finished:'완료'},andMore:n=>`외 ${n}개`,updated:a=>`${a}에 마지막 업데이트됨`},
  'pt-BR':{locale:'pt-BR',title:n=>n,resetting:'Renovando…',resetsIn:m=>`Renova em ${m} min`,
      resetsAt:t=>`Renova às ${t}`,resetsOn:(d,t)=>`Renova ${d} às ${t}`,resetsDate:d=>`Renova ${d}`,
      ago:m=>m<60?`há ${m} min`:`há ${Math.round(m/60)} h`,
      usedLeft:(used,left)=>`${used}% usado · ${left}% restante`,
      left:v=>`${v}% restante`,resets:n=>n===1?'1 renovação disponível':`${n} renovações disponíveis`,until:d=>`até ${d}`,never:'Não expira',unknown:'Validade desconhecida',
      kick:{warning:'Aviso de uso',limit:'Limite atingido',waiting:'Precisa de você',finished:'Concluído'},andMore:n=>`e mais ${n}`},
  en:{locale:'en-US',title:n=>n,resetting:'Resetting…',resetsIn:m=>`Resets in ${m} min`,
      resetsAt:t=>`Resets at ${t}`,resetsOn:(d,t)=>`Resets ${d} ${t}`,resetsDate:d=>`Resets ${d}`,
      ago:m=>m<60?`${m}m ago`:`${Math.round(m/60)}h ago`,
      usedLeft:(used,left)=>`${used}% used · ${left}% left`,
      left:v=>`${v}% left`,resets:n=>`${n} ${n===1?'reset':'resets'} available`,until:d=>`until ${d}`,never:'Doesn’t expire',unknown:'Expiry unknown',
      kick:{warning:'Usage warning',limit:'Limit reached',waiting:'Needs you',finished:'Finished'},andMore:n=>`and ${n} more`,updated:a=>`Updated ${a}`},
  uk:{locale:'uk-UA',title:n=>n,resetting:'Скидання…',resetsIn:m=>`Скидання через ${m} хв`,
      resetsAt:t=>`Скидання о ${t}`,resetsOn:(d,t)=>`Скидання: ${d} ${t}`,resetsDate:d=>`Скидання: ${d}`,
      ago:m=>m<60?`${m} хв тому`:`${Math.round(m/60)} год тому`,
      usedLeft:(used,left)=>`Використано ${used}% · лишилось ${left}%`,
      left:v=>`лишилось ${v}%`,resets:n=>`Доступно скидань: ${n}`,until:d=>`до ${d}`,never:'Без терміну',unknown:'Термін невідомий',
      kick:{warning:'Попередження',limit:'Ліміт вичерпано',waiting:'Потрібна увага',finished:'Готово'},andMore:n=>`і ще ${n}`,updated:a=>`Оновлено ${a}`},
  ru:{locale:'ru-RU',title:n=>n,resetting:'Сброс…',resetsIn:m=>`Сброс через ${m} мин`,
      resetsAt:t=>`Сброс в ${t}`,resetsOn:(d,t)=>`Сброс: ${d} ${t}`,resetsDate:d=>`Сброс: ${d}`,
      ago:m=>m<60?`${m} мин назад`:`${Math.round(m/60)} ч назад`,
      usedLeft:(used,left)=>`Использовано ${used}% · осталось ${left}%`,
      left:v=>`осталось ${v}%`,resets:n=>`Доступно сбросов: ${n}`,until:d=>`до ${d}`,never:'Бессрочно',unknown:'Срок неизвестен',
      kick:{warning:'Предупреждение',limit:'Лимит исчерпан',waiting:'Нужно внимание',finished:'Готово'},andMore:n=>`и ещё ${n}`,updated:a=>`Обновлено ${a}`},
  zh:{locale:'zh-CN',title:n=>n,resetting:'正在重置…',resetsIn:m=>`${m} 分钟后重置`,
      resetsAt:t=>`${t} 重置`,resetsOn:(d,t)=>`${d} ${t} 重置`,resetsDate:d=>`${d} 重置`,
      ago:m=>m<60?`${m} 分钟前`:`${Math.round(m/60)} 小时前`,
      usedLeft:(used,left)=>`已用 ${used}% · 剩余 ${left}%`,
      left:v=>`剩余 ${v}%`,resets:n=>`可用重置 ${n} 次`,until:d=>`${d} 前有效`,never:'不会过期',unknown:'到期时间未知',
      kick:{warning:'用量提醒',limit:'已达上限',waiting:'需要你',finished:'已完成'},andMore:n=>`另有 ${n} 个`,updated:a=>`更新于 ${a}`},
  'zh-Hant':{locale:'zh-TW',title:n=>n,resetting:'正在重置…',resetsIn:m=>`${m} 分鐘後重置`,
      resetsAt:t=>`${t} 重置`,resetsOn:(d,t)=>`${d} ${t} 重置`,resetsDate:d=>`${d} 重置`,
      ago:m=>m<60?`${m} 分鐘前`:`${Math.round(m/60)} 小時前`,
      usedLeft:(used,left)=>`已用 ${used}% · 剩餘 ${left}%`,
      left:v=>`剩餘 ${v}%`,resets:n=>`可用重置 ${n} 次`,until:d=>`${d} 前有效`,never:'不會過期',unknown:'到期時間未知',
      kick:{warning:'用量提醒',limit:'已達上限',waiting:'需要你',finished:'已完成'},andMore:n=>`另有 ${n} 個`,updated:a=>`更新於 ${a}`},
};
function ui(){return UI[uiLang]||UI.en;}
function textCopy(value){
  if(!value) return '';
  const table=TEXT[uiLang];
  if(!table) return value;
  if(table[value]) return table[value];
  let out=String(value);
  for(const [re,to] of PATTERNS[uiLang]||[]) out=out.replace(re,to);
  return out;
}
